[build]
  publish = "public"              # Папка со статикой
  functions = "netlify/functions" # Папка с функциями
  command = "npm install"         # Устанавливаем зависимости

[dev]
  publish = "public"
  functions = "netlify/functions"
  targetPort = 3000

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[functions."send-reminders"]
  schedule = "0 7 * * *"